"""drop rtt obsolete

Revision ID: 0ad93aba5b07
Revises: a48d60a69965
Create Date: 2026-06-01 11:46:37.474238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad93aba5b07'
down_revision = 'a48d60a69965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heures_payees')
    with op.batch_alter_table('parametrage_annuel', schema=None) as batch_op:
        batch_op.drop_column('rtt_heures_defaut')
        batch_op.drop_column('rtt_heures_reference')
        batch_op.drop_column('rtt_calc_mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametrage_annuel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtt_calc_mode', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('rtt_heures_reference', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('rtt_heures_defaut', sa.INTEGER(), nullable=False))

    op.create_table('heures_payees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('annee', sa.INTEGER(), nullable=False),
    sa.Column('mois', sa.INTEGER(), nullable=False),
    sa.Column('heures_payees', sa.INTEGER(), nullable=False),
    sa.Column('heures_trajet', sa.INTEGER(), nullable=False),
    sa.Column('heures_travaillees', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), nullable=False),
    sa.Column('saisi_par_id', sa.INTEGER(), nullable=True),
    sa.Column('saisi_le', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'annee', 'mois', name='uq_heures_user_annee_mois')
    )
    # ### end Alembic commands ###
