"""initial_schema

Revision ID: 4d485302de07
Revises: 
Create Date: 2026-05-27 15:16:02.123433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d485302de07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conges_exceptionnels_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('unite', sa.String(length=10), nullable=False),
    sa.Column('plafond_annuel', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('interessement_periodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('base_points', sa.Integer(), nullable=False),
    sa.Column('plancher_points', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jours_feries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_ferie', sa.Date(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('auto_genere', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_ferie', name='uq_date_ferie')
    )
    op.create_table('parametrage_annuel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debut_exercice', sa.Date(), nullable=False),
    sa.Column('fin_exercice', sa.Date(), nullable=False),
    sa.Column('jours_conges_defaut', sa.Integer(), nullable=False),
    sa.Column('rtt_heures_defaut', sa.Integer(), nullable=False),
    sa.Column('rtt_calc_mode', sa.String(length=10), nullable=False),
    sa.Column('rtt_heures_reference', sa.Integer(), nullable=False),
    sa.Column('rtt_coef_surplus', sa.Float(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('identifiant', sa.String(length=100), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifiant')
    )
    op.create_table('allocations_conges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parametrage_id', sa.Integer(), nullable=False),
    sa.Column('jours_alloues', sa.Integer(), nullable=False),
    sa.Column('jours_anciennete', sa.Integer(), nullable=False),
    sa.Column('jours_report', sa.Integer(), nullable=False),
    sa.Column('rtt_heures_allouees', sa.Integer(), nullable=False),
    sa.Column('rtt_heures_reportees', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parametrage_id'], ['parametrage_annuel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'parametrage_id', name='uq_user_parametrage')
    )
    op.create_table('conges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('nb_jours_ouvrables', sa.Integer(), nullable=False),
    sa.Column('type_conge', sa.String(length=50), nullable=False),
    sa.Column('nb_heures_rtt', sa.Integer(), nullable=True),
    sa.Column('nb_heures_exceptionnelles', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('valide_par_responsable_id', sa.Integer(), nullable=True),
    sa.Column('valide_par_responsable_le', sa.DateTime(), nullable=True),
    sa.Column('valide_par_id', sa.Integer(), nullable=True),
    sa.Column('valide_le', sa.DateTime(), nullable=True),
    sa.Column('motif_refus', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['valide_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['valide_par_responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heures_payees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('heures_payees', sa.Integer(), nullable=False),
    sa.Column('heures_trajet', sa.Integer(), nullable=False),
    sa.Column('heures_travaillees', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('saisi_par_id', sa.Integer(), nullable=True),
    sa.Column('saisi_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'annee', 'mois', name='uq_heures_user_annee_mois')
    )
    op.create_table('interessement_regles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_id', sa.Integer(), nullable=False),
    sa.Column('type_absence', sa.String(length=50), nullable=False),
    sa.Column('points_par_jour', sa.Float(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['periode_id'], ['interessement_periodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periode_id', 'type_absence', name='uq_interessement_periode_type')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', name='uq_push_user_endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lue', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('conge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conge_id'], ['conges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))

    op.drop_table('push_subscriptions')
    op.drop_table('interessement_regles')
    op.drop_table('heures_payees')
    op.drop_table('conges')
    op.drop_table('allocations_conges')
    op.drop_table('users')
    op.drop_table('parametrage_annuel')
    op.drop_table('jours_feries')
    op.drop_table('interessement_periodes')
    op.drop_table('conges_exceptionnels_types')
    # ### end Alembic commands ###
