"""parametrage rtt seuil hebdo

Revision ID: 6c4c4dc24980
Revises: 0ad93aba5b07
Create Date: 2026-06-01 11:58:25.337742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4c4dc24980'
down_revision = '0ad93aba5b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametrage_annuel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtt_seuil_hebdo', sa.Integer(), nullable=False, server_default='35'))
        batch_op.add_column(sa.Column('rtt_heures_par_jour_absence', sa.Integer(), nullable=False, server_default='7'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametrage_annuel', schema=None) as batch_op:
        batch_op.drop_column('rtt_heures_par_jour_absence')
        batch_op.drop_column('rtt_seuil_hebdo')

    # ### end Alembic commands ###
