"""audit_logs

Revision ID: 924cdb477c72
Revises: b5a4d1d568e2
Create Date: 2026-05-27 15:35:19.794925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924cdb477c72'
down_revision = 'b5a4d1d568e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('acteur_id', sa.Integer(), nullable=True),
    sa.Column('acteur_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('cible_type', sa.String(length=40), nullable=True),
    sa.Column('cible_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acteur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_acteur_id'), ['acteur_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_cible_id'), ['cible_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_cree_le'), ['cree_le'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_cree_le'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_cible_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_acteur_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
