"""delegations

Revision ID: a48d60a69965
Revises: 924cdb477c72
Create Date: 2026-05-27 16:01:05.766152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48d60a69965'
down_revision = '924cdb477c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('suppleant_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suppleant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delegations_responsable_id'), ['responsable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegations_suppleant_id'), ['suppleant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegations_suppleant_id'))
        batch_op.drop_index(batch_op.f('ix_delegations_responsable_id'))

    op.drop_table('delegations')
    # ### end Alembic commands ###
