"""demi_journees

Revision ID: b5a4d1d568e2
Revises: 4d485302de07
Create Date: 2026-05-27 15:23:34.689864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a4d1d568e2'
down_revision = '4d485302de07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demi_journee_debut', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('demi_journee_fin', sa.String(length=15), nullable=True))
        batch_op.alter_column('nb_jours_ouvrables',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conges', schema=None) as batch_op:
        batch_op.alter_column('nb_jours_ouvrables',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('demi_journee_fin')
        batch_op.drop_column('demi_journee_debut')

    # ### end Alembic commands ###
